export const PRODUCT_TAGS = [
    'canadian',
    'certclean',
    'chemical free',
    'dairy free',
    'ewg verified',
    'ecocert',
    'fair trade',
    'gluten free',
    'hypoallergenic',
    'natural',
    'no talc',
    'non-gmo',
    'organic',
    'peanut free product',
    'sugar free',
    'usda organic',
    'vegan',
    'alcohol free',
    'cruelty free',
    'oil free',
    'purpicks',
    'silicone free',
    'water free',
];
