import React, { Fragment } from 'react';

import BrandLink from './../components/BrandLink';
import FactNumber from './../components/FactNumber';

const About = () => {
    return (
        <Fragment>
            <div className="flex items-center">
                <div className="relative my-20 mx-auto">
                    <div className="absolute bg-yellow h-14 rounded-full top-0 w-14 -z-1"></div>
                    <BrandLink classes="text-6xl ml-5" />
                </div>
            </div>
            <div className=" text-justify py-10">
                <div className="mx-auto w-2/3">
                    <p className="mb-4">
                        Welly is the leading premium beauty platform in Europe. Offering more than 130,000 beauty and
                        lifestyle products in online shops, the beauty marketplace and more than 2,000 stores, Welly
                        inspires customers to live their own kind of beauty by a previously unparalleled assortment.
                    </p>
                    <p>
                        The continued expansion of the fast-growing e‑commerce business is the focus of the
                        <span className="font-krona"> #forwardbeauty</span>. DigitalFirst strategy programme. In fiscal
                        year 2019/2020, Welly generated sales of 3.2 billion euros in the areas of perfumery, decorative
                        cosmetics, skin and hair care as well as nutritional supplements and accessories.
                        <span className="font-krona"> #letsdobeautiful</span>
                    </p>
                </div>
            </div>

            <div className="bg-yellow">
                <div className="flex flex-col md:flex-row space-y-10 md:space-y-0 py-10 w-3/4 mx-auto">
                    {/* Facts and figures */}
                    <FactNumber
                        icon={'people'}
                        number="20,000"
                        title="Beauty Experts"
                        description="strive to make their customers more beautiful and thus happier"
                    />
                    <FactNumber
                        icon={'revenue'}
                        number="3.2"
                        title="Billion Euros"
                        description="revenue was generated by Douglas in the 2019/20 financial year"
                    />
                    <FactNumber
                        icon={'shop'}
                        number="130,000"
                        title="Care Products"
                        description="because we care about you in online shops, and in stores"
                    />
                </div>
            </div>
            <div className="text-center w-2/3 mx-auto my-20">
                <h4 className="font-krona mb-4">Imprint</h4>
                <p>Welly Inc. Welly-Street 7-11 40235 Welland</p>
                <p>
                    You can reach us by email at: service@welly.wellly. Our deliveries go out every Sunday evening so
                    you can get them as early in the week as possible
                </p>
            </div>
        </Fragment>
    );
};

export default About;
